### ISSUE TITLE
WPS_PC运行报错

### ISSUE THREAD

**Issue by q123458384** [ytt447735/automation#2]
WPS_PC
```
Traceback (most recent call last):
  File "/ql/data/scripts/ytt447735_automation/wps.py", line 101, in <module>
    SenPC()
  File "/ql/data/scripts/ytt447735_automation/wps.py", line 71, in SenPC
    ck = pu.convert_cookies_to_dict(mt_token)
  File "/ql/data/scripts/ytt447735_automation/fun/pu.py", line 13, in convert_cookies_to_dict
    cookies = dict([l.split("=", 1) for l in cookies.replace(' ', '').split(";")])
ValueError: dictionary update sequence element #1 has length 1; 2 is required
```

**Comment by q123458384** [comment]
解决了，ua值里面不能包含`;` 
完整ua是`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.157`
只保留后半段就行了：`Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.157`

**Comment by 5jwoj** [comment]
export wps_pc='Chrome/73.0.3683.75 Safari/537.36;wps_sid=V02SJ9O-yNJOK8xxxxxxxxx3d05cb;'
我是这样填的，但报错
Traceback (most recent call last):
  File "wps.py", line 14, in <module>
    from fun import wpswx
ImportError: cannot import name 'wpswx' from 'fun' (/usr/lib/python3.8/site-packages/fun.py)

**Comment by leic4u** [comment]
wpsua 可以去 https://www.wps.cn 拿，拿到的是经过 base64 编码后的值。解码出来之后是 `WPSUA/1.0 (web-kdocs:Firefox_132.0; windows:Windows 10.0; ....` 这样的值。
![图片](https://github.com/user-attachments/assets/4e147108-a40a-49ca-a06e-602d80721494)
