### ISSUE TITLE
wps签到报错

### ISSUE THREAD

**Issue by qhq** [ytt447735/automation#23]
-------------------总共1个wps_PC CK-------------------
{"account":"","account_num":1,"***********,"uzone":"CN-HN"}
出错了！详细错误👇错误CK👉wpsua=V1BTVUEvMS4wICh3ZWIta2RvY3M6Q2hyb21lXzEzMi4wLjAuMDsgd2luZG93czpXaW5kb3dzIDEwLjA7IGZVZjF6ekVIVGlLOV9IZUpSNUU4dlE9PTpRMmh5YjIxbElD;wps_sid=V02SlN****55;
HTTPConnectionPool(host='cn-hk-bgp-4.ofalias.net', port=50818): Max retries exceeded with url: /inference_wps_pc (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6fc8d9c390>, 'Connection to cn-hk-bgp-4.ofalias.net timed out. (connect timeout=None)'))

提示这个是卡验证了吗

**Comment by qq846511277** [comment]
调用接口太频繁了
